# Generated by Django 5.0.7 on 2024-08-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Course", "0003_course_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cover",
            field=models.ImageField(null=True, upload_to="course_cover/"),
        ),
    ]
