# Generated by Django 5.0.7 on 2024-08-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Course", "0004_course_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="course_cover/"),
        ),
    ]
