# Generated by Django 5.0.7 on 2024-08-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Course", "0005_alter_course_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("ux design", "UX DESIGN"),
                    ("video editing", "VIDEO EDITING"),
                    ("web dev", "WEB DEV"),
                    ("hacking", "HACKING"),
                ],
                default="web dev",
                max_length=20,
            ),
        ),
    ]
