# Generated by Django 5.0.7 on 2024-07-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder',
            new_name='student',
        ),
    ]
