# Generated by Django 5.0.7 on 2024-08-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0003_student_better_than"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="type",
            field=models.CharField(
                choices=[("avarage", "Avarage"), ("good", "Good"), ("best", "Best")],
                default="good",
                max_length=20,
            ),
        ),
    ]
