# Generated by Django 5.0.7 on 2024-08-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0004_student_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pic"),
        ),
    ]
