# Generated by Django 5.0.7 on 2024-08-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0005_student_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="role",
            field=models.CharField(
                choices=[
                    ("web developer", "Web Developer"),
                    ("ux/ui designer", "UX/UI developer"),
                    ("hacker", "hacker"),
                ],
                default="web developer",
                max_length=20,
            ),
        ),
    ]
